### PR TITLE
Add support for source maps

### PR DESCRIPTION
**Pull request by arggh**
Refactored the process function to disable inline source maps, so that PostCSS will provide them separately in the result object.

### CODE REVIEW

**Comment by arggh** [comment]
Should also fix https://github.com/TehShrike/svelte-preprocess-postcss/issues/2 ?

**Comment by Kreozot** [comment]
@TehShrike Is it ready to merge?

**Comment by TehShrike** [comment]
I'm not sure how I missed this PR...

**Comment by TehShrike** [comment]
@arggh you used spaces for indentation 😂

**Pull request merged**
